<?php
include_once(realpath(dirname(__FILE__) . '/PkodalAssetGenerator.inc'));
include_once(realpath(dirname(__FILE__) . '/../../themes/ThemeFactory.inc'));
include_once(realpath(dirname(__FILE__) . '/../../framework/HtmlUtil.inc'));

include_once(realpath(dirname(__FILE__) . '/AssetFactory.inc'));
include_once(realpath(dirname(__FILE__) . '/factories/AutoAssetFactory.inc'));

include_once(realpath(dirname(__FILE__) . '/factories/SimpleAssetFactory.inc'));
include_once(realpath(dirname(__FILE__) . '/factories/MobileAssetFactory.inc'));

?>
