
<div class="detailsBox">
<span class="debug-header">Database details</span><br/>

<table>
<tr>
<td class="item">hostname</td><td class="data"><?php print DB_HOST; ?></td>
</tr>

<tr>
<td class="item">db name</td><td class="data"><?php print DB_DATABASE_NAME; ?></td>
</tr>

<tr>
<td class="item">username</td><td class="data"><?php print DB_USERNAME;?></td>	
</tr>

<tr>
<td class="item">password</td><td class="data"><?php print DB_PASSWD;?></td>
</tr>
</table>
</div>

