<html>
<head><title>Site Debug</title></head>
<body>
	<center>
	<h1>Debug</h1>
	</center>
        This is the Debug gateway.<br/>
        To use debug to load a module so you can test in isolation. prefix the module path with 'debug'.
        i.e., to go to '/feeds/events', go to to /debug/feeds/events'.<br/><br/>

        
        More handy debug info:<br/>
        <ul>
            <li><a href="?q=/debug/console">Debug console</a></li>
            <li><a href="?q=/debug/info">Framework modules and application config</a></li>
        </ul>        
</body>
</html>
