<?php 

/*
 * This file contains config constants. 
 */

// dispatcher properties

define("QUERY_PARAM", "q");
define("DEFAULT_MODULE", "homepage");
define("ERROR_CONTROLLER", "controllers/ErrorController.php");
define("VERBOSE_EXCEPTIONS", true);



// DB properties
define("DB_HOST", "localhost");
define("DB_DATABASE_NAME", "keystone");
define("DB_USERNAME", "root");
define("DB_PASSWD", "root");
define("PROXY_NAMESPACE", "Keystone\Proxies");


//Custom properties
define("DEV_MODE", true);

// USER DEFINED PROPERTIES GO HERE

?>
